arrowParens: avoid
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
printWidth: 100
semi: false
singleQuote: true
trailingComma: all
useTabs: true
